trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
- group: fractalize-variables

- name: buildConfiguration
  value: 'Release'
- name: solution
  value: 'src/DevCracks.Fractalize.Framework.sln'
- name: project
  value: 'src/DevCracks.Fractalize.Infrastructure/DevCracks.Fractalize.Infrastructure.csproj'
- name: packageVersion
  value: '1.0.$(Build.BuildId)'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore $(solution)
  displayName: 'Restore dependencies'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build solution'

- script: dotnet pack $(project) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(packageVersion)
  displayName: 'Create NuGet package'

- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop

- task: NuGetAuthenticate@1
  displayName: 'Authenticate to NuGet feed'

- task: NuGetCommand@2
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishFeed: '$(NUGET_FEED_ID)'
    versioningScheme: 'off'
